import * as fc from "fast-check";
import deepEqual from "deep-equal";

/**
 * Create an arbitrary of lists from a list of arbitraries.
 */
export function concatArbitrary<A>(
  arbitraries: fc.Arbitrary<A>[],
): fc.Arbitrary<A[]> {
  return arbitraries.reduce((acc, arb) => {
    return acc.chain(l => arb.map(a => l.concat(a)));
  }, fc.constant([]) as fc.Arbitrary<A[]>);
}

/**
 * A sanity check, checking whether values generated by this arbitrary
 * are equal to themselves.
 */
export function equalitySanityCheck<A>(arb: fc.Arbitrary<A>) {
  fc.assert(fc.property(arb, (a) => deepEqual(a, a)));
}

/**
 * Sample an arbitrary and show samples with given show function.
 */
export function sampleShow<A, B>(
  arb: fc.Arbitrary<A>,
  showF: (a: A) => B,
) {
  fc.sample(arb)
    .map(x => showF(x))
    .forEach(x => {
      console.log(JSON.stringify(x));
    });
}

